######################################################################
# Automatically generated by qmake (2.01a) mer. août 14 11:47:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
