######################################################################
# Automatically generated by qmake (2.01a) ven. août 2 03:22:43 2013
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += screenshot.h
SOURCES += main.cpp screenshot.cpp
