######################################################################
# Automatically generated by qmake (2.01a) ven. août 9 05:32:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS +=
SOURCES += main.cpp
