######################################################################
# Automatically generated by qmake (2.01a) lun. août 12 07:57:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += configwindow.h
SOURCES += configwindow.cpp main.cpp
