######################################################################
# Automatically generated by qmake (2.01a) mer. juil. 17 00:31:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
