######################################################################
# Automatically generated by qmake (2.01a) lun. août 12 03:25:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += webkit